import { NextResponse } from "next/server"

export async function GET() {
  try {
    // Expanded product catalog with more variety
    const mockData = [
      {
        Product_Name: "Strawberries",
        Catagory: "Fruits & Vegetables",
        Supplier_Name: "Fresh Farms Co",
        Warehouse_Location: "32525 Marquette Park",
        Status: "Active",
        Product_ID: "01-903-5373",
        Supplier_ID: "37-902-0286",
        Date_Received: "2024-05-25",
        Last_Order_Date: "2024-05-20",
        Expiration_Date: "2024-06-05",
        Stock_Quantity: 94,
        Reorder_Level: 77,
        Reorder_Quantity: 89,
        Unit_Price: 6.0,
        Sales_Volume: 40,
        Inventory_Turnover_Rate: 84,
        percentage: "-325%",
        Days_to_Expiry: 4,
        Turnover_Rate: 0.42,
        Stock_Value: 564.0,
      },
      {
        Product_Name: "Organic Bananas",
        Catagory: "Fruits & Vegetables",
        Supplier_Name: "Green Valley Organic",
        Warehouse_Location: "15420 Oak Street",
        Status: "Active",
        Product_ID: "02-445-1122",
        Supplier_ID: "22-334-5566",
        Date_Received: "2024-05-28",
        Last_Order_Date: "2024-05-25",
        Expiration_Date: "2024-06-08",
        Stock_Quantity: 156,
        Reorder_Level: 50,
        Reorder_Quantity: 100,
        Unit_Price: 2.5,
        Sales_Volume: 65,
        Inventory_Turnover_Rate: 92,
        percentage: "15%",
        Days_to_Expiry: 7,
        Turnover_Rate: 0.41,
        Stock_Value: 390.0,
      },
      {
        Product_Name: "Greek Yogurt",
        Catagory: "Dairy",
        Supplier_Name: "Mountain Dairy",
        Warehouse_Location: "8890 Dairy Lane",
        Status: "Active",
        Product_ID: "03-778-9900",
        Supplier_ID: "44-556-7788",
        Date_Received: "2024-05-30",
        Last_Order_Date: "2024-05-28",
        Expiration_Date: "2024-06-12",
        Stock_Quantity: 78,
        Reorder_Level: 30,
        Reorder_Quantity: 60,
        Unit_Price: 4.99,
        Sales_Volume: 25,
        Inventory_Turnover_Rate: 68,
        percentage: "8%",
        Days_to_Expiry: 11,
        Turnover_Rate: 0.32,
        Stock_Value: 389.22,
      },
      {
        Product_Name: "Whole Wheat Bread",
        Catagory: "Bakery",
        Supplier_Name: "Artisan Bakery",
        Warehouse_Location: "5567 Baker Street",
        Status: "Active",
        Product_ID: "04-123-4567",
        Supplier_ID: "11-222-3333",
        Date_Received: "2024-06-01",
        Last_Order_Date: "2024-05-30",
        Expiration_Date: "2024-06-04",
        Stock_Quantity: 45,
        Reorder_Level: 20,
        Reorder_Quantity: 40,
        Unit_Price: 3.49,
        Sales_Volume: 18,
        Inventory_Turnover_Rate: 75,
        percentage: "-12%",
        Days_to_Expiry: 3,
        Turnover_Rate: 0.4,
        Stock_Value: 157.05,
      },
      {
        Product_Name: "Premium Ground Coffee",
        Catagory: "Beverages",
        Supplier_Name: "Mountain Roasters",
        Warehouse_Location: "9876 Coffee Ave",
        Status: "Active",
        Product_ID: "05-987-6543",
        Supplier_ID: "55-666-7777",
        Date_Received: "2024-05-20",
        Last_Order_Date: "2024-05-15",
        Expiration_Date: "2024-08-15",
        Stock_Quantity: 120,
        Reorder_Level: 40,
        Reorder_Quantity: 80,
        Unit_Price: 12.99,
        Sales_Volume: 35,
        Inventory_Turnover_Rate: 45,
        percentage: "22%",
        Days_to_Expiry: 75,
        Turnover_Rate: 0.29,
        Stock_Value: 1558.8,
      },
      {
        Product_Name: "Fresh Salmon Fillet",
        Catagory: "Seafood",
        Supplier_Name: "Ocean Fresh",
        Warehouse_Location: "2234 Harbor View",
        Status: "Active",
        Product_ID: "06-234-7890",
        Supplier_ID: "88-999-1111",
        Date_Received: "2024-06-01",
        Last_Order_Date: "2024-05-31",
        Expiration_Date: "2024-06-03",
        Stock_Quantity: 32,
        Reorder_Level: 15,
        Reorder_Quantity: 25,
        Unit_Price: 18.99,
        Sales_Volume: 12,
        Inventory_Turnover_Rate: 95,
        percentage: "-45%",
        Days_to_Expiry: 2,
        Turnover_Rate: 0.37,
        Stock_Value: 607.68,
      },
      {
        Product_Name: "Organic Spinach",
        Catagory: "Fruits & Vegetables",
        Supplier_Name: "Green Valley Organic",
        Warehouse_Location: "15420 Oak Street",
        Status: "Active",
        Product_ID: "07-345-8901",
        Supplier_ID: "22-334-5566",
        Date_Received: "2024-05-30",
        Last_Order_Date: "2024-05-29",
        Expiration_Date: "2024-06-06",
        Stock_Quantity: 67,
        Reorder_Level: 25,
        Reorder_Quantity: 50,
        Unit_Price: 3.99,
        Sales_Volume: 28,
        Inventory_Turnover_Rate: 78,
        percentage: "-18%",
        Days_to_Expiry: 5,
        Turnover_Rate: 0.41,
        Stock_Value: 267.33,
      },
      {
        Product_Name: "Aged Cheddar Cheese",
        Catagory: "Dairy",
        Supplier_Name: "Artisan Cheese Co",
        Warehouse_Location: "4455 Dairy Farm Rd",
        Status: "Active",
        Product_ID: "08-456-9012",
        Supplier_ID: "33-444-6677",
        Date_Received: "2024-05-15",
        Last_Order_Date: "2024-05-10",
        Expiration_Date: "2024-07-15",
        Stock_Quantity: 89,
        Reorder_Level: 30,
        Reorder_Quantity: 60,
        Unit_Price: 8.99,
        Sales_Volume: 22,
        Inventory_Turnover_Rate: 52,
        percentage: "35%",
        Days_to_Expiry: 44,
        Turnover_Rate: 0.24,
        Stock_Value: 800.11,
      },
      {
        Product_Name: "Sourdough Bread",
        Catagory: "Bakery",
        Supplier_Name: "Artisan Bakery",
        Warehouse_Location: "5567 Baker Street",
        Status: "Active",
        Product_ID: "09-567-0123",
        Supplier_ID: "11-222-3333",
        Date_Received: "2024-06-01",
        Last_Order_Date: "2024-05-31",
        Expiration_Date: "2024-06-05",
        Stock_Quantity: 38,
        Reorder_Level: 15,
        Reorder_Quantity: 30,
        Unit_Price: 4.99,
        Sales_Volume: 16,
        Inventory_Turnover_Rate: 82,
        percentage: "-22%",
        Days_to_Expiry: 4,
        Turnover_Rate: 0.42,
        Stock_Value: 189.62,
      },
      {
        Product_Name: "Organic Milk",
        Catagory: "Dairy",
        Supplier_Name: "Pure Farms Dairy",
        Warehouse_Location: "7788 Meadow Lane",
        Status: "Active",
        Product_ID: "10-678-1234",
        Supplier_ID: "55-666-8899",
        Date_Received: "2024-05-29",
        Last_Order_Date: "2024-05-27",
        Expiration_Date: "2024-06-10",
        Stock_Quantity: 124,
        Reorder_Level: 40,
        Reorder_Quantity: 80,
        Unit_Price: 5.49,
        Sales_Volume: 45,
        Inventory_Turnover_Rate: 88,
        percentage: "12%",
        Days_to_Expiry: 9,
        Turnover_Rate: 0.36,
        Stock_Value: 680.76,
      },
      {
        Product_Name: "Free-Range Eggs",
        Catagory: "Dairy",
        Supplier_Name: "Happy Hen Farm",
        Warehouse_Location: "9900 Farm Road",
        Status: "Active",
        Product_ID: "11-789-2345",
        Supplier_ID: "66-777-9900",
        Date_Received: "2024-05-28",
        Last_Order_Date: "2024-05-26",
        Expiration_Date: "2024-06-18",
        Stock_Quantity: 156,
        Reorder_Level: 50,
        Reorder_Quantity: 100,
        Unit_Price: 6.99,
        Sales_Volume: 38,
        Inventory_Turnover_Rate: 65,
        percentage: "28%",
        Days_to_Expiry: 17,
        Turnover_Rate: 0.24,
        Stock_Value: 1090.44,
      },
      {
        Product_Name: "Avocados",
        Catagory: "Fruits & Vegetables",
        Supplier_Name: "Tropical Imports",
        Warehouse_Location: "1122 Import Blvd",
        Status: "Active",
        Product_ID: "12-890-3456",
        Supplier_ID: "77-888-0011",
        Date_Received: "2024-05-31",
        Last_Order_Date: "2024-05-29",
        Expiration_Date: "2024-06-07",
        Stock_Quantity: 89,
        Reorder_Level: 30,
        Reorder_Quantity: 60,
        Unit_Price: 1.99,
        Sales_Volume: 42,
        Inventory_Turnover_Rate: 89,
        percentage: "-8%",
        Days_to_Expiry: 6,
        Turnover_Rate: 0.47,
        Stock_Value: 177.11,
      },
      {
        Product_Name: "Chicken Breast",
        Catagory: "Meat",
        Supplier_Name: "Farm Fresh Poultry",
        Warehouse_Location: "3344 Poultry Lane",
        Status: "Active",
        Product_ID: "13-901-4567",
        Supplier_ID: "88-999-2222",
        Date_Received: "2024-06-01",
        Last_Order_Date: "2024-05-30",
        Expiration_Date: "2024-06-05",
        Stock_Quantity: 67,
        Reorder_Level: 25,
        Reorder_Quantity: 50,
        Unit_Price: 9.99,
        Sales_Volume: 28,
        Inventory_Turnover_Rate: 76,
        percentage: "-15%",
        Days_to_Expiry: 4,
        Turnover_Rate: 0.41,
        Stock_Value: 669.33,
      },
      {
        Product_Name: "Blueberries",
        Catagory: "Fruits & Vegetables",
        Supplier_Name: "Berry Best Farms",
        Warehouse_Location: "5566 Berry Hill",
        Status: "Active",
        Product_ID: "14-012-5678",
        Supplier_ID: "99-000-3333",
        Date_Received: "2024-05-30",
        Last_Order_Date: "2024-05-28",
        Expiration_Date: "2024-06-06",
        Stock_Quantity: 78,
        Reorder_Level: 30,
        Reorder_Quantity: 60,
        Unit_Price: 7.99,
        Sales_Volume: 32,
        Inventory_Turnover_Rate: 81,
        percentage: "-12%",
        Days_to_Expiry: 6,
        Turnover_Rate: 0.41,
        Stock_Value: 623.22,
      },
      {
        Product_Name: "Artisan Pasta",
        Catagory: "Pantry",
        Supplier_Name: "Italian Imports",
        Warehouse_Location: "7788 Little Italy",
        Status: "Active",
        Product_ID: "15-123-6789",
        Supplier_ID: "00-111-4444",
        Date_Received: "2024-05-20",
        Last_Order_Date: "2024-05-15",
        Expiration_Date: "2024-12-20",
        Stock_Quantity: 145,
        Reorder_Level: 50,
        Reorder_Quantity: 100,
        Unit_Price: 3.99,
        Sales_Volume: 25,
        Inventory_Turnover_Rate: 35,
        percentage: "65%",
        Days_to_Expiry: 202,
        Turnover_Rate: 0.17,
        Stock_Value: 578.55,
      },
    ]

    return NextResponse.json(mockData)
  } catch (error) {
    console.error("Error loading products:", error)
    return NextResponse.json({ error: "Failed to load products" }, { status: 500 })
  }
}
